
###  Brands ###  Brands ###  Brands ###  Brands

GET  {{host}}/api/brands
Accept: application/json

### Get all brands
GET  {{host}}/api/brands/zZgfSF3CKDuZChpwG
Accept: application/json

### Get brand by id

POST   {{host}}/api/brands
Content-Type: application/json

{"name": "pUMa"}

###Add new brand


PUT   {{host}}/api/brands/zZgfSF3CKDuZChpwG
Content-Type: application/json

{"name": "Adidas"}
###Edit  brand name

DELETE   {{host}}/api/brands/MTk6MPcp4CWmwN3ZTde
Content-Type: application/json

###Delete brand








###  Category ###  Category ###  Category ###  Category
GET  {{host}}/api/category/
Accept: application/json

### get all category

GET  {{host}}/api/category/bsiMfhvbB5ypXW2ge
Accept: application/json

### get  a category by id

GET  {{host}}/api/category/sub_Category/GaQkR6sesk6PGL3bo
Accept: application/json

### get sub category of a given parent id

GET  {{host}}/api/category/root_category/
Accept: application/json

### get  all header cateogry
POST   {{host}}/api/category/
Content-Type: application/json

{
  "name": "troll",
  "parent": ""
}

###add Category

PUT   {{host}}/api/category/GaQkR6sesk6PGL3bo
Content-Type: application/json

{
  "name": "",
  "parent": "/"
}
###Edit  category


DELETE   {{host}}/api/category/GaQkR6sesk6PGL3bo
Content-Type: application/json

###Delete category
















###  Criteria ###  Criteria ###  Criteria ###  Criteria

GET  {{host}}/api/criteria/
Accept: application/json

### get all criteria

GET  {{host}}/api/criteria/Wn3nveoYBskpzTYeF
Accept: application/json

### get  a criteria by id

### get  all header cateogry
POST   {{host}}/api/criteria/
Content-Type: application/json

{
  "name": "size",
  "value": ["xs","s","m","l","xl","xxl","xxl"],
  "isColor":false
}

###add criteria

PUT   {{host}}/api/criteria/Wn3nveoYBskpzTYeF
Content-Type: application/json

{
  "name": "size",
  "isColor": false
}
###Edit  criteria name and is color


DELETE   {{host}}/api/criteria/RWytJFqgqNhpQ3mfN
Content-Type: application/json

###Delete criteria

PUT   {{host}}/api/criteria/Wn3nveoYBskpzTYeF/value
Content-Type: application/json

{
  "value":["m"]
}
###add value of criteria to the array note dosent add duplicated values or already inserted


DELETE  {{host}}/api/criteria/Wn3nveoYBskpzTYeF/value
Content-Type: application/json

{
  "value":["troll","trol2"]
}
###add value of criteria to the array








###  Products ###  Products ###  Products ###  Products
GET {{host}}/api/products
Accept: application/json

### Get all products

GET {{host}}/api/products/brand/zZgfSF3CKDuZChpwG
Accept: application/json

### Get all products with the specific brand
GET {{host}}/api/products/category/dPamQbbFR
Accept: application/json

### Get all products with the specific Category

GET {{host}}/api/products/PWiQYmyvuas6jbc62
Accept: application/json

### Get all product by id


POST   {{host}}/api/products
Content-Type: application/json

{
  "name": "pull",
  "price": 1,
  "stock": 50,
  "description": "THis Product is the best",
  "brandId": "zZgfSF3CKDuZChpwG",
  "category": ["dPamQbbFRTNqXffwG"],
  "criteria": ["Wn3nveoYBskpzTYeF"]
}

### add new  product


PUT   {{host}}/api/products/PWiQYmyvuas6jbc62
Content-Type: application/json

{
  "name": "pull",
  "price": 2,
  "stock": 60,
  "description": "THis Product is  the best",
  "brandId": "zZgfSF3CKDuZChpwG+1",
  "category": ["dPamQbbFRTNqXffwG"],
  "criteria": ["Wn3nveoYBskpzTYeF"]
}

### add new  product


DELETE   {{host}}/api/products/QdacDjxMzpgYbeHgM
Content-Type: application/json

###Delete product

