
###  Brands ###  Brands ###  Brands ###  Brands

GET  {{host}}/api/brands
Accept: application/json

### Get all brands
GET  {{host}}/api/brands/zZgfSF3CKDuZChpwG
Accept: application/json

### Get brand by id

POST   {{host}}/api/brands
Content-Type: application/json

{"name": "pUMa"}

###Add new brand


PUT   {{host}}/api/brands/zZgfSF3CKDuZChpwG
Content-Type: application/json

{"name": "Adidas"}
###Edit  brand name

DELETE   {{host}}/api/brands/MTk6MPcp4CWmwN3ZTde
Content-Type: application/json

###Delete brand

###  Category ###  Category ###  Category ###  Category

POST   {{host}}/api/category/
Content-Type: application/json

{
  "name": "jeans",
  "parent": ""
}

###add Category

GET  {{host}}/api/category/
Accept: application/json

### get all category

GET  {{host}}/api/category/bsiMfhvbB5ypXW2ge
Accept: application/json

### get  a category by id

GET  {{host}}/api/category/sub_Category/2Z758ggq5Q7wsGX4T
Accept: application/json

### get sub category of a given parent id

GET  {{host}}/api/category/root_category/
Accept: application/json

### get  all header cateogry
























###  Products ###  Products ###  Products ###  Products
GET {{host}}/api/products
Accept: application/json

### Get all products

GET {{host}}/api/products/:id
Accept: application/json

### Get all product by id


